sylius_grid:
  grids:
    wkdks_example:
      driver:
        name: doctrine/orm
        options:
          class: Wkdks\SyliusExamplePlugin\Entity\Configuration
      limits: [25, 50, 100, 200]
      fields:
        name:
          type: string
          label: wkdks_example.ui.form.name
        description:
          type: string
          label: wkdks_example.ui.form.description
        fromDate:
          type: datetime
          label: wkdks_example.ui.form.from
        toDate:
          type: datetime
          label: wkdks_example.ui.form.to
        enabled:
          type: twig
          label: wkdks_example.ui.form.enabled
          options:
            template: SyliusUiBundle:Grid/Field:enabled.html.twig
        customersOnly:
          type: twig
          label: wkdks_example.ui.form.customers_only
          options:
            template: WkdksSyliusExamplePlugin:Grid/Field:customers_only.html.twig
      actions:
        main:
          create:
            type: create
            label: wkdks_example.ui.actions.create
        item:
          update:
            type: update
          delete:
            type: delete
      filters:
        name:
          type: string
          label: wkdks_example.ui.form.name
        description:
          type: string
          label: wkdks_example.ui.form.description
        enabled:
          type: boolean
          label: wkdks_example.ui.form.enabled
        customersOnly:
          type: boolean
          label: wkdks_example.ui.form.customers_only
        fromDate:
          type: date
          label: wkdks_example.ui.form.from
        toDate:
          type: date
          label: wkdks_example.ui.form.to
